#!/usr/bin/env bash
# fizzbuzz
x=1
while ((x <= 100))
do
	if ((x % 15))
	then
		echo "FizzBuzz"
	elif ((x % 3))
	then 
		echo "Fizz"
	elif ((x % 5))
	then 
		echo "Buzz"
	else 
		echo $x
	fi
((x++)) 
done
