#!/usr/bin/env bash
# fizzbuzz
x=1
while [ $x -le 100 ]
do
	echo $x
	if [ $x % 15 ]
	then
		echo "FizzBuzz"
	fi
	if [ $x % 3 ]
	then 
		echo "Fizz"
	fi
	if [ $x % 5 ]
	then 
		echo "Buzz"
	fi
	((x++)) 
done
