#!/usr/bin/env bash
# 4 is bad luck, 8 is your chance
x=1
while [ $x -lt 11 ]
do 
	if [[ "$x" == '4' ]]
	then
		echo "bad luck"
		break
	elif [[ "$x" == '8' ]]
	then
		echo "good luck"
		break
	else
		echo "Best School"
	((x++))
fi
done
