#!/usr/bin/env bash
# superstitious numbers
x=1
while [ $x -lt 21 ]
do
	echo $x
	case $x in
	
	4) echo $x
	echo -n "bad luck from China"
	;;

	9) echo $x
	echo -n "bad luck from Japan"
	;;

	17) echo $x
	echo -n "bad luck from Italy"
	;;
esac

((x++))

done	
