#!/usr/bin/env bash
# superstitious numbers
x=1
while [ $x -lt 21 ]
do
	echo $x
case $x in

	
	4)
	echo -n "bad luck from China" \n
	;;

	9)
	echo -n "bad luck from Japan" \n
	;;

	17)
	echo -n "bad luck from Italy" \n
	;;
esac

((x++))

done	
